/**
 * Created by xiongjian on 2018/5/10.
 */
export const CREATE_USER = 'CREATE_USER'
export const FETCH_USER = 'FETCH_USER'
export const DELETE_USER = 'DELETE_USER'

export const CREATE_USER_MODEL = 'CREATE_USER_MODEL'
export const FETCH_USER_MODEL = 'FETCH_USER_MODEL'
export const DELETE_USER_MODEL = 'DELETE_USER_MODEL'


export const CREATE_TOKEN = 'CREATE_TOKEN'
export const FETCH_TOKEN = 'FETCH_TOKEN'
export const DELETE_TOKEN = 'DELETE_TOKEN'

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER'
export const FETCH_CUSTOMER   = 'FETCH_CUSTOMER'
export const UPDATE_CUSTOMER  = 'UPDATE_CUSTOMER'
export const DELETE_CUSTOMER  = 'DELETE_CUSTOMER'

export const UPDATE_PAGESTATE  = 'UPDATE_PAGESTATE'

export const SET_HEADMENU  = 'SET_HEADMENU'

export const CREATE_PENDING_ACT_NUM = 'CREATE_PENDING_ACT_NUM'
export const FETCH_PENDING_ACT_NUM = 'FETCH_PENDING_ACT_NUM'
export const DELETE_PENDING_ACT_NUM = 'DELETE_PENDING_ACT_NUM'

export const CREATE_ALERT = 'CREATE_ALERT'
export const DELETE_ALERT = 'DELETE_ALERT'

export const SET_PROJECT = 'SET_PROJECT'

export const SET_PLATFORM = 'SET_PLATFORM'
export const FETCH_PLATFORM = 'FETCH_PLATFORM'

export const CREATE_URL_PARAMS = 'CREATE_URL_PARAMS'
export const FETCH_URL_PARAMS = 'FETCH_URL_PARAMS'
export const DELETE_URL_PARAMS = 'DELETE_URL_PARAMS'

export const CREATE_LAST_LOGIN_AS = 'CREATE_LAST_LOGIN_AS'
export const FETCH_LAST_LOGIN_AS = 'FETCH_LAST_LOGIN_AS'
export const DELETE_LAST_LOGIN_AS = 'DELETE_LAST_LOGIN_AS'

export const SET_WXOPENID = 'SET_WXOPENID'
export const FETCH_WXOPENID = 'FETCH_WXOPENID'
export const DELETE_WXOPENID = 'DELETE_WXOPENID'
